# Generated by Django 5.0.4 on 2024-08-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='pointsHave',
            new_name='pointsToGive',
        ),
        migrations.AddField(
            model_name='works',
            name='timeToJob',
            field=models.IntegerField(default=1, verbose_name='Время сколько нужно отработать'),
        ),
    ]
