# Generated by Django 5.0.4 on 2024-08-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_pointshave_works_pointstogive_works_timetojob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pointsHave',
            field=models.IntegerField(default=0),
        ),
    ]
