# Generated by Django 5.0.4 on 2024-08-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_baseuser_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
    ]
